[project]
name = "asitop"
version = "0.0.23"
description = "Performance monitoring CLI tool for Apple Silicon"
license = "MIT"
readme = "README.md"
requires-python = ">=3.8"
keywords = ["asitop"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: MacOS",
]
dependencies = [
    "blessed",
    "dashing",
    "psutil",
    "wcwidth",
]

[project.scripts]
asitop = "asitop.asitop:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
